name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build and Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    needs: run-tests

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/orangecountylettings:latest


