name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    name: Run Tests & Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with flake8
        run: flake8 .

      - name: Run tests with coverage
        env:
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
        run: pytest --cov --cov-report=term-missing

  deploy:
    name: Build and Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    needs: run-tests
    if: github.ref == 'refs/heads/main' && success()

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/orangecountylettings:latest
            ${{ secrets.DOCKER_USERNAME }}/orangecountylettings:${{ github.sha }}
          build-args: |
            SECRET_KEY=${{ secrets.SECRET_KEY }}
            DEBUG=False
            SENTRY_DSN=${{ secrets.SENTRY_DSN }}
